### PR TITLE
Polluted fish

### PR DESCRIPTION
**Pull request by WVCSergkart**
Added the ability to fish in polluted water if there is polluted fish there.

Also added gitignore

### CODE REVIEW

**Comment by juanosarg** [comment]
From what I'm seeing, this seems to do more things than adding polluted fish

**Comment by WVCSergkart** [comment]
Yes and no. Removed all the junk for gitignore. And merged all the zone update requests into one. Pollution check, fish update and ocean check. 

https://github.com/WVCSergkart/VanillaFishingExpanded/blob/main/1.5/Source/VCE-Fishing/VCE-Fishing/Commands/Command_SetFishList.cs
https://github.com/WVCSergkart/VanillaFishingExpanded/blob/main/1.5/Source/VCE-Fishing/VCE-Fishing/Zones/Zone_Fishing.cs
https://github.com/WVCSergkart/VanillaFishingExpanded/blob/main/1.5/Source/VCE-Fishing/VCE-Fishing/Defs/FishDef.cs
````
public void InitialSetZoneFishList()
{
    fishInThisZone = new();
    isZonePolluted = false;
    if (this.cells.Count < Options.VCE_Fishing_Settings.VCEF_minimumZoneSize)
    {
        isZoneBigEnough = false;
    }
    else
    {
        isZoneBigEnough = true;
        if (ModsConfig.BiotechActive)
        {
            foreach (IntVec3 cell in this.cells)
            {
                if (cell.IsPolluted(this.Map))
                {
                    isZonePolluted = true;
                    break;
                }
            }
        }
        bool considerPrecepts = false;
        Ideo ideo = null;
        if (ModsConfig.IdeologyActive)
        {
            ideo = Current.Game.World.factionManager.OfPlayer.ideos.PrimaryIdeo;
            considerPrecepts = true;
        }
        int index = 0;
        while (index < cells.Count)
        {
            if (cells[index].GetTerrain(Map) == TerrainDefOf.WaterOceanDeep || cells[index].GetTerrain(Map) == TerrainDefOf.WaterOceanShallow)
            {
                isOcean = true;
                break;
            }
            index++;
            isOcean = false;
        }
        foreach (FishDef element in DefDatabase<FishDef>.AllDefs.Where(element => element.fishSizeCategory == this.fishSizeToCatch))
        {
            bool flagNoPrecepts = false;
            if (considerPrecepts && element.preceptsRequired != null)
            {
                foreach (string requiredPrecept in element.preceptsRequired)
                {
                    if (ideo.HasPrecept(DefDatabase<PreceptDef>.GetNamedSilentFail(requiredPrecept)))
                    {
                        flagNoPrecepts = true;
                    }
                }
            }
            else { flagNoPrecepts = true; }
            if (flagNoPrecepts)
            {
                if (element.anyBiomeAllowed)
                {
                    AddFish(element);
                }
                else
                {
                    foreach (string biomeTemp in element.allowedBiomes)
                    {
                        foreach (BiomeTempDef biometempdef in DefDatabase<BiomeTempDef>.AllDefs.Where(biometempdef => biometempdef.biomeTempLabel == biomeTemp))
                        {
                            foreach (string biome in biometempdef.biomes)
                            {
                                if (this.Map.Biome.defName == biome)
                                {
                                    AddFish(element);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if (fishInThisZone.Count > 0)
    {
        isZoneEmpty = false;
    } 
    else isZoneEmpty = true;
}

private void AddFish(FishDef element)
{
    if (!element.allowPolluted && isZonePolluted || element.onlyPolluted && !isZonePolluted)
    {
        return;
    }
    if (this.isOcean && element.canBeSaltwater)
    {
        this.fishInThisZone.Add(element.thingDef);
    }
    if (!this.isOcean && element.canBeFreshwater)
    {
        this.fishInThisZone.Add(element.thingDef);
    }
}
````
Also, the fishing permission request was changed, nests were removed from it, and individual requests to zone bools were merged into one. 
````
public bool AllowFishing
{
    get
    {
        if (someoneFishing)
        {
            return false;
        }
        if (!allowFishing)
        {
            return false;
        }
        if (!isZoneBigEnough)
        {
            return false;
        }
        if (isZoneEmpty)
        {
            return false;
        }
        return true;
    }
}
````

https://github.com/WVCSergkart/VanillaFishingExpanded/blob/main/1.5/Source/VCE-Fishing/VCE-Fishing/AI/WorkGiver_Fish.cs
````
if (fishingZone.AllowFishing && !fishingZone.ContainsStaticFire && pawn.CanReserveAndReach(fishingZone.Cells[0], PathEndMode.OnCell, maxDanger))
{
    for (int k = 0; k < fishingZone.cells.Count; k++)
    {
        yield return fishingZone.cells[k];
    }
}
````

Changed the request in MapComponent, now it just requests Zone_Fishing update directly from the zone.
https://github.com/WVCSergkart/VanillaFishingExpanded/blob/main/1.5/Source/VCE-Fishing/VCE-Fishing/MapComponents/FishingMapComponent.cs
Also, the update frequency was changed, since zones do not change often, high frequency is not necessary for them.

The number of changes looks large due to the deleted .vs and .obj folders that the repositories do not need.

Reading the code and looking at what it does, in some places I moved lines and deleted empty fields, but I did not touch the functionality.

**Comment by juanosarg** [comment]
Merged it! If something breaks you are fixing it XDDD

**Comment by WVCSergkart** [comment]
Okie-doki :D

**Pull request merged**
